"""Energy-Signal Aware Scheduler — telemetry, carbon trace, API client, scheduling policies."""
from hasagi.energy.background import BackgroundModel, marginal_kwh_from_trace
from hasagi.energy.carbon_sources import (
    AggregateCarbonReading,
    CarbonReading,
    CarbonSource,
    ElectricityMapsClient,
    IEAStaticSource,
    MultiSourceCarbonAggregator,
    WattTimeClient,
)
from hasagi.energy.carbon_trace import CarbonTrace, load_csv_trace, synthetic_solar_trace
from hasagi.energy.marginal_meter import MarginalEnergyMeter
from hasagi.energy.pod_ledger import (
    PHASE_ACTIVE,
    PHASE_COLD_START,
    PHASE_IDLE,
    LedgerReport,
    PhaseInterval,
    PodEnergyLedger,
    nvml_cumulative_kwh_fn,
)
from hasagi.energy.policy import (
    EnergyDecision,
    MPCPolicy,
    OnlinePrimalDualPolicy,
    PowerAwareRulePolicy,
    RuleBasedPolicy,
)
from hasagi.energy.regime import (
    GpuRegime,
    RegimeCarbon,
    break_even_window_s,
    regime_breakdown,
    regime_carbon,
)
from hasagi.energy.rl_policy import (
    OBSERVATION_DIM,
    PPOAction,
    PPOObservation,
    PPOScalingPolicy,
    build_observation,
    compute_reward,
    discrete_action_space_size,
)
from hasagi.energy.telemetry import (
    AggregateTelemetrySource,
    FakeTelemetrySource,
    FakeWorker,
    NvmlTelemetrySource,
    PrometheusPusher,
    RaplTelemetrySource,
    TelemetrySource,
    WorkerTelemetry,
)
from hasagi.energy.throttle_pareto import (
    CapPoint,
    PolicyResult,
    PowerCapProfile,
    pareto,
    simulate_masked_policy,
    simulate_policy,
)
from hasagi.energy.trace_schedule import (
    GRID_ZONE_IDS,
    ZoneTrace,
    diurnal_offsets,
    find_zone_csv,
    load_zone_traces,
    quantile_threshold,
    rotate,
    trace_to_hourly,
    zone_stats,
)

__all__ = [
    "OBSERVATION_DIM",
    "AggregateCarbonReading",
    "AggregateTelemetrySource",
    "BackgroundModel",
    "CapPoint",
    "CarbonReading",
    "CarbonSource",
    "CarbonTrace",
    "ElectricityMapsClient",
    "EnergyDecision",
    "FakeTelemetrySource",
    "FakeWorker",
    "GRID_ZONE_IDS",
    "GpuRegime",
    "IEAStaticSource",
    "LedgerReport",
    "MPCPolicy",
    "MarginalEnergyMeter",
    "MultiSourceCarbonAggregator",
    "NvmlTelemetrySource",
    "OnlinePrimalDualPolicy",
    "PHASE_ACTIVE",
    "PHASE_COLD_START",
    "PHASE_IDLE",
    "PhaseInterval",
    "PodEnergyLedger",
    "PolicyResult",
    "RegimeCarbon",
    "PPOAction",
    "PPOObservation",
    "PPOScalingPolicy",
    "PowerAwareRulePolicy",
    "PowerCapProfile",
    "PrometheusPusher",
    "RaplTelemetrySource",
    "RuleBasedPolicy",
    "TelemetrySource",
    "WattTimeClient",
    "WorkerTelemetry",
    "ZoneTrace",
    "break_even_window_s",
    "build_observation",
    "compute_reward",
    "discrete_action_space_size",
    "diurnal_offsets",
    "find_zone_csv",
    "load_csv_trace",
    "load_zone_traces",
    "marginal_kwh_from_trace",
    "nvml_cumulative_kwh_fn",
    "pareto",
    "quantile_threshold",
    "regime_breakdown",
    "regime_carbon",
    "rotate",
    "simulate_masked_policy",
    "simulate_policy",
    "synthetic_solar_trace",
    "trace_to_hourly",
    "zone_stats",
]
